server:
  port: 12002
  bes:
    accept-count: 1000
    min-spare-threads: 20
    max-threads: 4000
    max-connections: 20000
logging:
  file: /tsf-demo-logs/${spring.application.name}/root.log
  level:
    root: INFO
